# Generated by Django 3.1.4 on 2020-12-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instauser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
